# Configuration file for mapping of Thetered-TRIP experiments performed in K562 cells.
# This configuration contains all configurations used by the pipeline.
# Different parts of the pipeline use this configuration:
#
# snakemake:
#   this part mainly contains input files and a description of each file
#   the following input files are used:
#     - cDNA:
#         fastq files with cDNA reads of barcoded reporters
#     - gDNA:
#         fastq files with gDNA reads of barcoded reporters used to normalize the cDNA (cDNA) reads
#     - spike-in:
#         fastq file with only reads of the spike-in library which was mixed in with the cDNA and gDNA reads.
#     - forward_mapping:
#         fastq files with forward iPCR reads of reporter integrations containing barcodes.
#     - reverse_mapping:
#         fastq files with reverse iPCR reads of reporter integrations with intergration site.

###############################
### snakemake configuration ###
###############################
dir_suffix: 'TTRIP_F1mESC'

# groups:
#   - [clone, cl3, cl18, cl19, cl23, wt]
#   - [condition, ctrl, GAL4-KRAB]
#   - [replicate, r1, r2]


input_file:
  mapping:
    cl1:
      - [cl20170329_raw_mapping_F1mESC_with_failed/4276_1_BarcodedPool_NoIndex_cl1_R1.fq.gz, cl20170329_raw_mapping_F1mESC_with_failed/4276_1_BarcodedPool_NoIndex_cl1_R2.fq.gz]
      - 10
    cl3:
      - [cl20170329_raw_mapping_F1mESC_with_failed/4276_1_BarcodedPool_NoIndex_cl3_R1.fq.gz, cl20170329_raw_mapping_F1mESC_with_failed/4276_1_BarcodedPool_NoIndex_cl3_R2.fq.gz]
      - 10
    cl12:
      - [cl20170329_raw_mapping_F1mESC_with_failed/4276_1_BarcodedPool_NoIndex_cl12_R1.fq.gz, cl20170329_raw_mapping_F1mESC_with_failed/4276_1_BarcodedPool_NoIndex_cl12_R2.fq.gz]
      - 10
    cl18:
      - [cl20170329_raw_mapping_F1mESC_with_failed/4276_1_BarcodedPool_NoIndex_cl18_R1.fq.gz, cl20170329_raw_mapping_F1mESC_with_failed/4276_1_BarcodedPool_NoIndex_cl18_R2.fq.gz]
      - 10
    cl19:
      - [cl20170329_raw_mapping_F1mESC_with_failed/4276_1_BarcodedPool_NoIndex_cl19_R1.fq.gz, cl20170329_raw_mapping_F1mESC_with_failed/4276_1_BarcodedPool_NoIndex_cl19_R2.fq.gz]
      - 10
    cl20:
      - [cl20170329_raw_mapping_F1mESC_with_failed/4276_1_BarcodedPool_NoIndex_cl20_R1.fq.gz, cl20170329_raw_mapping_F1mESC_with_failed/4276_1_BarcodedPool_NoIndex_cl20_R2.fq.gz]
      - 10
    cl23:
      - [cl20170329_raw_mapping_F1mESC_with_failed/4276_1_BarcodedPool_NoIndex_cl23_R1.fq.gz, cl20170329_raw_mapping_F1mESC_with_failed/4276_1_BarcodedPool_NoIndex_cl23_R2.fq.gz]
      - 10
  polyA:
    cl3_ctrl_r1:
      - /home/NFS/users/r.kluin/Shares/RUN662_for_Laura_Brueckner/4287_1_CM1411_r1_GTGGCCT_S37_L004_R1_001.fastq.gz
      - 0
    cl3_ctrl_r2:
      - /home/NFS/users/r.kluin/Shares/RUN662_for_Laura_Brueckner/4287_2_CM1411_r2_GTTTCGG_S38_L004_R1_001.fastq.gz
      - 0
    cl18_ctrl_r1:
      - /home/NFS/users/r.kluin/Shares/RUN662_for_Laura_Brueckner/4287_3_CM1416_r1_CGTACGT_S39_L004_R1_001.fastq.gz
      - 0
    cl18_ctrl_r2:
      - /home/NFS/users/r.kluin/Shares/RUN662_for_Laura_Brueckner/4287_4_CM1416_r2_GAGTGGA_S40_L004_R1_001.fastq.gz
      - 0
    cl19_ctrl_r1:
      - /home/NFS/users/r.kluin/Shares/RUN662_for_Laura_Brueckner/4287_5_CM1417_r1_ACTGATA_S41_L004_R1_001.fastq.gz
      - 0
    cl19_ctrl_r2:
      - /home/NFS/users/r.kluin/Shares/RUN662_for_Laura_Brueckner/4287_6_CM1417_r2_ATTCCTT_S42_L004_R1_001.fastq.gz
      - 0
    cl23_ctrl_r1:
      - /home/NFS/users/r.kluin/Shares/RUN662_for_Laura_Brueckner/4287_7_CM1420_r1_CGATGTA_S43_L004_R1_001.fastq.gz
      - 0
    cl23_ctrl_r2:
      - /home/NFS/users/r.kluin/Shares/RUN662_for_Laura_Brueckner/4287_8_CM1420_r2_TGACCAA_S44_L004_R1_001.fastq.gz
      - 0
    wt_ctrl_r1:
      - /home/NFS/users/r.kluin/Shares/RUN662_for_Laura_Brueckner/4287_9_WT_r1_ACAGTGA_S45_L004_R1_001.fastq.gz
      - 0
    wt_ctrl_r2:
      - /home/NFS/users/r.kluin/Shares/RUN662_for_Laura_Brueckner/4287_10_WT_r2_GCCAATA_S46_L004_R1_001.fastq.gz
      - 0
    cl3_GAL4-KRAB_r1:
      - /home/NFS/users/r.kluin/Shares/RUN668_for_Laura_Brueckner/4318_1_CM1411_plb129_r1_CAGATCA_S1_L001_R1_001.fastq.gz
      - 0
    cl3_GAL4-KRAB_r2:
      - /home/NFS/users/r.kluin/Shares/RUN668_for_Laura_Brueckner/4318_2_CM1411_plb129_r2_CTTGTAA_S2_L001_R1_001.fastq.gz
      - 0
    cl18_GAL4-KRAB_r1:
      - /home/NFS/users/r.kluin/Shares/RUN668_for_Laura_Brueckner/4318_3_CM1416_plb129_r1_AGTCAAC_S3_L001_R1_001.fastq.gz
      - 0
    cl18_GAL4-KRAB_r2:
      - /home/NFS/users/r.kluin/Shares/RUN668_for_Laura_Brueckner/4318_4_CM1416_plb129_r2_AGTTCCG_S4_L001_R1_001.fastq.gz
      - 0
    cl19_GAL4-KRAB_r1:
      - /home/NFS/users/r.kluin/Shares/RUN668_for_Laura_Brueckner/4318_5_CM1417_plb129_r1_ATGTCAG_S5_L001_R1_001.fastq.gz
      - 0
    cl19_GAL4-KRAB_r2:
      - /home/NFS/users/r.kluin/Shares/RUN668_for_Laura_Brueckner/4318_6_CM1417_plb129_r2_CCGTCCC_S6_L001_R1_001.fastq.gz
      - 0
    cl23_GAL4-KRAB_r1:
      - /home/NFS/users/r.kluin/Shares/RUN668_for_Laura_Brueckner/4318_7_CM1420_plb129_r1_GTCCGCA_S7_L001_R1_001.fastq.gz
      - 0
    cl23_GAL4-KRAB_r2:
      - /home/NFS/users/r.kluin/Shares/RUN668_for_Laura_Brueckner/4318_8_CM1420_plb129_r2_GTGAAAC_S8_L001_R1_001.fastq.gz
      - 0



#
# config: cl20160816_config_K562_TTRIP.txt
#
# intersect:
#   repeat: '{outdir}/repeats.bed'
#   lad: /home/NFS/users/c.leemans/data/carolineLADs/LAD_K562_continuous_cl160714.bed
#   chrom: /home/NFS/users/c.leemans/data/tracks/hg19/wgEncodeBroadHmmK562HMM.bed
#
# extract:
#   timing: /home/NFS/users/c.leemans/data/tracks/hg19/GSM923448/GSM923448_hg19_wgEncodeUwRepliSeqK562{state}PctSignalRep1.bigWig
#
# nearest:
#   cpg: /home/NFS/users/c.leemans/data/tracks/hg19/cpgIslandExtUnmasked_140601.bed
#
# repeatMasker: /home/NFS/users/c.leemans/data/tracks/hg19/repeatMasker_hg19_fa_out_20140131.bed

###############################################################################
###++++++++++++++++++++++++++++ parser settings ++++++++++++++++++++++++++++###
###############################################################################
# Typical structure of gDNA and cDNA reads:
#      index            pat1               barcode           pat2
# NNNNNNNNNNGTCACAAGGGCCGGCCACAACTCGAGNNNNNNNNNNNNNNNNTGATCCTGCAGTGTCACC...
#
# settings:
#   barcode_length -- the length of the barcode
#   pat1 -- the first constant pattern (after index, before barcode)
#   pat2 -- the pattern after the barcode
# #****************************************************************************
# Typical structures of mapping reads
#
# Forward Read:
#
# format_map1
#      index   	        pat1             barcode     pat2		genomic DNA
# NNNNNNNNNNGTCACAAGGGCCGGCCACAACTCGAGNNNNNNNNNNNNNNNNTGATCNNNNNNNNNNNNNNNNNNNN
#
# Reverse Read:
# 	     map_pat_rev					     genomic DNA
# GTACGTCACAATATGATTATCTTTCTAGGGTTAANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

structure:
  mapping: |
    ID      5'      3'      type    req     second-read     pos   keep-bases
    index   %i      -       const   present False   fixed   -
    map_pat1a       GTCANAAGGGCCGGCCACAAC   -       const   present False   fixed   -
    const_bar       TCGAG\{16\}TGATC  -       const_bar       present False   fixed   -
    rev_map_complement      -       TTAACCCTAGAAAGATAATCATATTGTGACGTAC      const   -       False   var   -
    rev_map GTACGTNANAATATGATTATCTTTCTAGGGTTAA      -       const   present True    fixed   -
    fwd_map_complement      -       GATCA[BC]CTCGAGTTGTGGCCGGCCCTTGTGAC     const_bar_comp  -       True    var   -

  gDNA: |
    ID      5'      3'      type    req     second-read     pos                   keep-bases
    index   %i      -       const   present   False   fixed   -
    pat1    GTCACAAGGGCCGGCCACAACTCGAG      -       const   present False   fixed   -
    barcode 16      -       barcode present False   fixed   -
    pat2    TGATCCTGCAGTG   -       const   present False   var   -

  cDNA: |
    ID      5'      3'      type    req     second-read     pos     keep-bases
    index   %i      -       const   present False   fixed   -
    pat1    GTCACAAGGGCCGGCCACAACTCGAG      -       const   present False   fixed   -
    barcode 16      -       barcode present False   fixed   -
    pat2    TGATCCTGCAGTG   -       const   present False   var   -

  polyA: |
    ID      5'      3'      type    req     second-read     pos     keep-bases
    index   %i      -       const   present False   fixed   -
    pat1    TTTACGCCAGGGTTTTCCCAGTCACAAGGGCCGGCCACAACTCGAG  -  const  present  False  var  -
    const_bar \{16\}TGATCC  -  const_bar  present  False  fixed  -

  spike: |
    ID      5'      3'      type    req     second-read     pos     keep-bases
    index   %i      -       const   present False   fixed   -
    pat1    GTCACAAGGGCCGGCCACAA    -       const   present False   fixed   -
    barcode 16      -       barcode present False   fixed   -
    pat2    GATCGGTACCCA    -       const   present False   var   -

lev_dist: 2

min_count:
  spike: 1000
  gDNA: 5
  cDNA: 0
  polyA: 0
  map: 3

bowtie:
  index:  /home/NFS/users/j.yanez/data/genomes/bowtie2/mm10
  options:
      '1': ['--very-sensitive-local']
      '2': ['--very-sensitive-local']

fasta:
    '/home/NFS/users/c.leemans/data/GRCm38/GRCm38_68.fa'

vcf:
    129S1: '/home/NFS/users/c.leemans/data/GRCm38/129S1_SvImJ.mgp.v5.snps_indels.dbSNP142.vcf.gz'
    CAST: '/home/NFS/users/c.leemans/data/GRCm38/CAST_EiJ.mgp.v5.snps_indels.dbSNP142.vcf.gz'


max_dist:
  '1': 500
  '2': 20
