# Configuration file for mapping of Thetered-TRIP experiments performed in K562 cells.
# This configuration contains all configurations used by the pipeline.
# Different parts of the pipeline use this configuration:
#
# snakemake:
#   this part mainly contains input files and a description of each file
#   the following input files are used:
#     - cDNA:
#         fastq files with cDNA reads of barcoded reporters
#     - gDNA:
#         fastq files with gDNA reads of barcoded reporters used to normalize the cDNA (cDNA) reads
#     - spike-in:
#         fastq file with only reads of the spike-in library which was mixed in with the cDNA and gDNA reads.
#     - forward_mapping:
#         fastq files with forward iPCR reads of reporter integrations containing barcodes.
#     - reverse_mapping:
#         fastq files with reverse iPCR reads of reporter integrations with intergration site.

###############################
### snakemake configuration ###
###############################
dir_suffix: 'TTRIP_RPE'

groups:
  - [replicate, 1, 2]


input_file:
  gDNA:
    RPE_r1:
      - /home/NFS/users/l.brueckner/TTRIP_RPE/4242_1_BarcodedPool_NoIndex_RPE_r1_gDNA.fq
      - 10
    RPE_r2:
      - /home/NFS/users/l.brueckner/TTRIP_RPE/4242_1_BarcodedPool_NoIndex_RPE_r2_gDNA.fq
      - 10
  cDNA:
    RPE_r1:
      - /home/NFS/users/l.brueckner/TTRIP_RPE/4242_1_BarcodedPool_NoIndex_RPE_r1_cDNA.fq
      - 10
    RPE_r2:
      - /home/NFS/users/l.brueckner/TTRIP_RPE/4242_1_BarcodedPool_NoIndex_RPE_r2_cDNA.fq
      - 10
#
# config: cl20160816_config_K562_TTRIP.txt
#
# intersect:
#   repeat: '{outdir}/repeats.bed'
#   lad: /home/NFS/users/c.leemans/data/carolineLADs/LAD_K562_continuous_cl160714.bed
#   chrom: /home/NFS/users/c.leemans/data/tracks/hg19/wgEncodeBroadHmmK562HMM.bed
#
# extract:
#   timing: /home/NFS/users/c.leemans/data/tracks/hg19/GSM923448/GSM923448_hg19_wgEncodeUwRepliSeqK562{state}PctSignalRep1.bigWig
#
# nearest:
#   cpg: /home/NFS/users/c.leemans/data/tracks/hg19/cpgIslandExtUnmasked_140601.bed
#
# repeatMasker: /home/NFS/users/c.leemans/data/tracks/hg19/repeatMasker_hg19_fa_out_20140131.bed

###############################################################################
###++++++++++++++++++++++++++++ parser settings ++++++++++++++++++++++++++++###
###############################################################################
# Typical structure of gDNA and cDNA reads:
#      index            pat1               barcode           pat2
# NNNNNNNNNNGTCACAAGGGCCGGCCACAACTCGAGNNNNNNNNNNNNNNNNTGATCCTGCAGTGTCACC...
#
# settings:
#   barcode_length -- the length of the barcode
#   pat1 -- the first constant pattern (after index, before barcode)
#   pat2 -- the pattern after the barcode
# #****************************************************************************
# Typical structures of mapping reads
#
# Forward Read:
#
# format_map1
#      index   	        pat1             barcode     pat2		genomic DNA
# NNNNNNNNNNGTCACAAGGGCCGGCCACAACTCGAGNNNNNNNNNNNNNNNNTGATCNNNNNNNNNNNNNNNNNNNN
#
# Reverse Read:
# 	     map_pat_rev					     genomic DNA
# GTACGTCACAATATGATTATCTTTCTAGGGTTAANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

structure:
  mapping: |

  gDNA: |
    ID      5'      3'      type    req     second-read     pos                   keep-bases
    index   %i      -       const   present False   fixed                            -
    pat1    GTCACAAGGGCCGGCCACAACTCGAG      -       const   present False   fixed   -
    barcode 16      -       barcode present False   fixed   -
    pat2    TGATCCTGCAGTG   -       const   present False   var   -

  cDNA: |
    ID      5'      3'      type    req     second-read     pos     keep-bases
    index   %i      -       const   present False   fixed   -
    pat1    GTCACAAGGGCCGGCCACAACTCGAG      -       const   present False   fixed   -
    barcode 16      -       barcode present False   fixed   -
    pat2    TGATCCTGCAGTG   -       const   present False   var   -

  spike: |
    ID      5'      3'      type    req     second-read     pos     keep-bases
    index   %i      -       const   present False   fixed   -
    pat1    GTCACAAGGGCCGGCCACAA    -       const   present False   fixed   -
    barcode 16      -       barcode present False   fixed   -
    pat2    GATCGGTACCCA    -       const   present False   var   -

lev_dist: 2

min_count:
  spike: 1000
  gDNA: 5
  cDNA: 0
  map: 3

bowtie:
  index: /home/NFS/users/j.yanez/data/genomes/bowtie2/hg19
  options:
      '1': ['--very-sensitive']
      '2': ['--very-sensitive-local']


max_dist_for: 500

max_dist_rev: 20
